/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AppIndexImport } from './routes/app/index'
import { Route as AppTasksImport } from './routes/app/tasks'
import { Route as AppProjectsImport } from './routes/app/projects'
import { Route as AppClientsImport } from './routes/app/clients'
import { Route as AppMeetingsImport } from './routes/app/meetings'
import { Route as AppCalendarImport } from './routes/app/calendar'
import { Route as AppDocumentsImport } from './routes/app/documents'
import { Route as AppResearchImport } from './routes/app/research'
import { Route as AppFinanceImport } from './routes/app/finance'
import { Route as AppOperationsImport } from './routes/app/operations'
import { Route as AppActivityImport } from './routes/app/activity'
import { Route as AppSettingsImport } from './routes/app/settings'

// Create Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRoute,
} as any)

const AppTasksRoute = AppTasksImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => rootRoute,
} as any)

const AppProjectsRoute = AppProjectsImport.update({
  id: '/app/projects',
  path: '/app/projects',
  getParentRoute: () => rootRoute,
} as any)

const AppClientsRoute = AppClientsImport.update({
  id: '/app/clients',
  path: '/app/clients',
  getParentRoute: () => rootRoute,
} as any)

const AppMeetingsRoute = AppMeetingsImport.update({
  id: '/app/meetings',
  path: '/app/meetings',
  getParentRoute: () => rootRoute,
} as any)

const AppCalendarRoute = AppCalendarImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => rootRoute,
} as any)

const AppDocumentsRoute = AppDocumentsImport.update({
  id: '/app/documents',
  path: '/app/documents',
  getParentRoute: () => rootRoute,
} as any)

const AppResearchRoute = AppResearchImport.update({
  id: '/app/research',
  path: '/app/research',
  getParentRoute: () => rootRoute,
} as any)

const AppFinanceRoute = AppFinanceImport.update({
  id: '/app/finance',
  path: '/app/finance',
  getParentRoute: () => rootRoute,
} as any)

const AppOperationsRoute = AppOperationsImport.update({
  id: '/app/operations',
  path: '/app/operations',
  getParentRoute: () => rootRoute,
} as any)

const AppActivityRoute = AppActivityImport.update({
  id: '/app/activity',
  path: '/app/activity',
  getParentRoute: () => rootRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRoute,
} as any)

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppIndexRoute,
  AppTasksRoute,
  AppProjectsRoute,
  AppClientsRoute,
  AppMeetingsRoute,
  AppCalendarRoute,
  AppDocumentsRoute,
  AppResearchRoute,
  AppFinanceRoute,
  AppOperationsRoute,
  AppActivityRoute,
  AppSettingsRoute,
])
